services:
  _defaults:
    autowire: true
    autoconfigure: true

  Sng\AdditionalReports\Controller\ReportController: ~

  Sng\AdditionalReports\Service\ContentTypeResolver: ~

  Sng\AdditionalReports\Service\ExtensionIconResolver: ~

  Sng\AdditionalReports\Service\ExtensionSchemaParser: ~

  Sng\AdditionalReports\Service\EventListenerRegistry: ~

  Sng\AdditionalReports\Service\Typo3VersionInformationService: ~

  Sng\AdditionalReports\Service\TerArchiveService: ~

  Sng\AdditionalReports\Repository\ContentUsageRepository: ~

  Sng\AdditionalReports\Repository\PageStatisticsRepository: ~

  Sng\AdditionalReports\Repository\ExtensionRepository: ~

  Sng\AdditionalReports\Repository\DatabaseStatusRepository: ~

  Sng\AdditionalReports\Repository\LogErrorRepository: ~

  Sng\AdditionalReports\Repository\WebsiteConfigurationRepository: ~

  Sng\AdditionalReports\Reports\CommandControllers:
    public: true

  Sng\AdditionalReports\Reports\Eid:
    public: true

  Sng\AdditionalReports\Reports\EventDispatcher:
    public: true

  Sng\AdditionalReports\Reports\Extensions:
    public: true

  Sng\AdditionalReports\Reports\Hooks:
    public: true

  Sng\AdditionalReports\Reports\LogErrors:
    public: true

  Sng\AdditionalReports\Reports\Middlewares:
    public: true

  Sng\AdditionalReports\Reports\Plugins:
    public: true

  Sng\AdditionalReports\Reports\Status:
    public: true

  Sng\AdditionalReports\Reports\WebsiteConf:
    public: true

  Sng\AdditionalReports\Reports\Xclass:
    public: true
